### ISSUE TITLE
Event timeline

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools#99]
## General Todos

 - [x] Setup panel + state boilerplate (#108)
 - [ ] Optimise position and element calculations

## Events
Events demonstrate what is happening on the stream

### Todo
 - [x] Add events (addition, update, teardown) (#108)
 - [x] Show tooltip on hover (needs design work)

### Screenshots

![Stream events](https://user-images.githubusercontent.com/10779424/76512907-63551080-644d-11ea-9a9b-ae40c40938a7.png)

## Stream periods
Stream periods demonstrate key durations within a stream (network requests, aliveness, etc)

 - [x] Add stream alive periods (#108)
 - [ ] Add network periods
 - [ ] Show tooltip on hover (needs design work)

### Screenshots

![Stream periods](https://user-images.githubusercontent.com/10779424/76512885-5a643f00-644d-11ea-88e0-87025aa614c1.png)

## Tooltips
Tooltips explain what different elements on the timeline are.

> Note: Tooltips don't provide operation-specific info

### Todo
 - [x] Create tooltip component (visual)
 - [x] Create tooltip hook (positioning)
 - [x] Add tooltips to event elements

## Event Panel

Shown when a user clicks on an element in the timeline.

### Todo

- [x] Add collapsible heading component  (@wgolledge)
- [ ] Add _Query_ + _Response_ sections to panel (@wgolledge)
- [ ] Hook panel into page 

### Screenshots

![Screenshot 2020-03-16 at 12 11 16](https://user-images.githubusercontent.com/10779424/76757464-89e1b700-677f-11ea-8e28-48f4fd60f648.png)

### Screenshots

![Tooltips](https://user-images.githubusercontent.com/10779424/76512853-4ddfe680-644d-11ea-8073-bce9ae3b4831.png)

## Timeline page

Shows all timelines on the page

### Todo

- [ ] Show all timelines (@andyrichardson)
- [x] Add ticker for time duration (@andyrichardson)

### Screenshots

![Screenshot 2020-03-16 at 12 15 07](https://user-images.githubusercontent.com/10779424/76757624-cca38f00-677f-11ea-8167-a7097a0f6337.png) 

## Additional info

![Timeline](https://user-images.githubusercontent.com/10779424/76513047-97303600-644d-11ea-942c-dda4caf8214a.png)
